version: "3"
services:
        mysql:
                image: mysql:latest
                ports:
                        - "3306:3306"
                environment:
                    MYSQL_ROOT_PASSWORD: rootpassword
                    MYSQL_DATABASE: opencart
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: admin
        app:
                image: apache-opencart
                ports:
                        - "4000:80"
                links:
                        - mysql
